##commande de bases
alias gis="gisele"
alias cpr="cp -r"
alias t3="tree -L 3"
alias t2="tree -L 2"
alias s="source"
alias sz="source ~/.zshrc"
alias ag="shellaliasgrep" #alias grep
alias c="cd"
alias clr="clear && pwd"
alias ch="chmod"
alias ic="ifconfig"
alias mkd="mkdir"
alias o="open"
alias open="echo '##### use o #####' && open"
alias p="pwd"
alias rmr="sudo rm -r"
alias va="vim_alias"
alias vh="vim_hc"
alias wg="wget"
alias wh="which"
alias uz="unzip"
alias e="echo"
alias fd="find"
function hosts(){ sudo echo " 127.0.0.1 $1" >> /etc/hosts }

#echo "$ ag || va"
