##commande de bases
alias gisele="php ~/scripts/gisele.phar -n --max-result=5 --format={counter}\ \[\ {title}\ \]\({link}\) web"
alias gis="gisele"
alias s="source"
alias sz="source ~/.zshrc"
alias ag="shellaliasgrep" #alias grep
alias c="clear;pwd"
alias ch="chmod"
alias ic="ifconfig"
alias mkd="mkdir"
alias mkdir="echo '###### use mkd #####' && mkdir"
alias o="open"
alias open="echo '##### use o #####' && open"
alias p="pwd"
alias rmr="sudo rm -r"
alias va="vim_alias"
alias vh="vim_hc"
alias wg="wget"
alias wh="which"
alias uz="unzip"
alias e="echo"

echo "$ ag || va"
