alias dcs="dev cd shopify"
alias dcp="dev cd partners"
alias dci="dev cd identity"
alias dcm="dev cd monorail"
alias u="breathe; dev up"
alias dt="deprecated spt"
alias opn="breathe; dev open"
alias opr="dev open pr"
