echo "db: $db tb: $tb"
function mysql_db() { mysql $db $1; }
alias my="m"
alias mdg="mysql -e 'show databases;' |grep"
alias msd="mysql -e 'show databases;'"
function mysql_create_database() { mysql -e "create database $1"; }
alias mcd="mysql_create_database"
alias m="mysql $db"
alias me="mysql $db -e "
alias mt="mysql $db -e 'show tables;'"
alias mtg="mysql $db -e 'show tables;' | grep"
export mds=" desc $tb"
export ms=" select * from $tb"
export msc=" select count(*) from $tb"
export msl="$ms limit 10"
export msw="$ms where "
export mup=" update $tb"
