alias be="bundle exec"
alias bec="bundle exec cucumber"
alias ber="bundle exec rspec"
alias berf="bundle exec rspec --fail-fast"
alias bun="bundle"
alias bui="bundle install"
alias r="rails"
alias rdc="rake db:create"
alias rdd="rake db:drop"
alias rdm="rake db:migrate"
alias rgc="rvm gemset create"
alias rgl="rvm gemset list" #gemsets
alias rgm=rails_generate_migration
function rails_generate_migration() { spring rails generate migration  $@ }
alias rgu="rvm gemset use"
alias rl="rvm list" # rubies
alias rr="rake routes"
alias rs="rails server"
alias rsp="rails server -p"
alias ru="rvm use"
alias rudev="rvm use ruby-2.2.0@dev"
alias rb="ruby -e"
alias srt=spring_rake_test
function spring_rake_test(){ spring rake test TEST=$(select_path $1 $2) && pronto run --index }
alias brt=bundle_rake_test
function bundle_rake_test(){ pronto run --index && select_path $1 $2 && bundle exec rake test TEST=$(select_path $1 $2) TESTOPTS='--verbose' }
alias srls='bundle exec spring rails'
alias srails='spring rails'
alias srake='spring rake'
alias srk='spring rake'
alias migrate='spring rake db:migrate'
alias mgrt='spring rake db:migrate'
