
## git ##
### fast version control ###
git-diff-name() { git diff $1 --name-only | cat }
alias gf="git flow"
alias gdn="git-diff-name"
alias gdnm="git-diff-name master"
alias g="git"
alias ga="git add"
alias gA="git add -A :/"
alias gAc="git add -A :/;git commit -m"
alias gAcn="git add -A :/;git commit -m 'no comments'"
alias gau="git add -u ."
alias gaU="git add -u :/"
alias gu="git-up"
alias gb="git branch"
alias gbv="git branch -v"
alias gbd="git branch -D"
alias gbm="git branch -m"
alias gbnm="git branch --no-merged"
alias gbanm="git branch --all --no-merged"
alias gbs="git branch --set-upstream-to="
alias gbl="git blame"
alias gc="git checkout "
alias gco="git config"
alias gcb="git checkout -b"
alias gcl="git clone "
alias gcm="git commit -m "
alias gd="git diff"
alias gd="git difftool"
alias gf="git fetch"
alias gfa="git fetch --all"
alias gi="git init"
alias gig="echo 'cp ~/gitignore/'| pbcopy && ls ~/gitignore |grep -i"
alias gl="git log"
alias gsw="git-sweep preview && git-sweep"
alias gp="git pull"
alias gP="git push"
alias gre="git reset"
alias gacp="git add -A :/; git commit -m 'no comment ';git push" #git add commit push (no comment)
alias gm="git merge"
alias gr="git remote"
alias gr="git remote -v"
alias gra="git remote add"
alias gs="git status"
alias gst="git stash"
alias gsta="git_stats"
alias gsh="git show"
alias gsp="git stash pop"
##git commande combinee
alias Gac="git add -u;git commit -m"
alias Gcm="git checkout master"
alias Gds="git diff;git status;git branch -v"
alias Gpm="git push origin master"
alias ghc="hub create" #git hub create

alias Gconf='git config --global color.ui true;git config --global user.name "Denis Laliberté",git config core.fileMode false'
