
alias t15="t timeline -l |grep http | head -15 | tail -10"
alias t2="t timeline -l |grep http | head -2"
alias t5="t timeline -l |grep http | head -5"
alias tf="t favorite"
alias tht="t timeline -l |grep http"
alias tme="t mentions"
alias tre="t retweet"
alias tu="t unfollow"
alias tw="t whois"
